name: ta_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rename: ^3.0.2
  http: ^1.4.0
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^30.1.37
  intl: ^0.20.2
  syncfusion_flutter_gauges: ^30.1.37
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.0
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  mqtt_client: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/LOGO.png
    - assets/ICON2.png
    - assets/images/default_avatar.png

  fonts:
    - family: Inter24
      fonts:
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
          weight: 800
    - family: Inter18
      fonts:
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

  generate: true

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: s.dart
  output-class: S


flutter_icons:
  xandroid: true
  ios: true
  image_path: "assets/ICON2.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/ICON2.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ICON2.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/ICON2.png"
  remove_alpha_ios: true

flutter_launcher_name:
  name: "Smart Power Management"

